CREATE DATABASE  IF NOT EXISTS `postalcode`;
USE `postalcode`;

DROP TABLE IF EXISTS `mut_straat`;

SET NAMES latin1;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `mut_straat` (
   TYPE char(8) NOT NULL,
  STREET_ID int(6) NOT NULL ,
  STREET_NAME_BAG varchar(80) NOT NULL,
  STREET_NAME_NEN varchar(24),
  PLACE_ID int(6),
  PRIMARY KEY (TYPE, STREET_ID),
  FOREIGN KEY(PLACE_ID) REFERENCES mut_plaats(PLACE_ID)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS = 1;

USE `postalcode`;

DROP TABLE IF EXISTS `mut_plaats`;

SET NAMES latin1;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE mut_plaats (
   TYPE char(8) NOT NULL,
  PLACE_ID int(6) NOT NULL ,
  PLACE_NAME_BAG varchar(80),
  PLACE_NAME_NEN varchar(24),
  PLACE_CODE int(4) ,
  CITY_ID INT(6),
  PRIMARY KEY (TYPE, PLACE_ID),
  FOREIGN KEY(CITY_ID) REFERENCES mut_gemeente(CITY_ID)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS = 1;

USE `postalcode`;

DROP TABLE IF EXISTS `mut_gemeente`;

SET NAMES latin1;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE mut_gemeente (
   TYPE char(8) NOT NULL,
  CITY_ID int(6) NOT NULL ,
  CITY_NAME_BAG varchar(80) ,
  CITY_NAME_NEN varchar(24),
  CITY_CODE int(4) ,
  CEBUCO_CODE INT(3),
  PROVINCE_CODE CHAR(1),
  PRIMARY KEY (TYPE, CITY_ID),
  FOREIGN KEY(PROVINCE_CODE) REFERENCES mut_province(PROVINCE_CODE)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS = 1;

USE `postalcode`;

DROP TABLE IF EXISTS `mut_pcreeks`;

SET NAMES latin1;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE mut_pcreeks (
   TYPE char(8) NOT NULL,
  POSTCODE_HOUSENO_ID int(6) NOT NULL ,
  AREA_CODE_NUMBER varchar(4) ,
  AREA_CODE_LETTER varchar(2),
  HOUSE_NUMBER_FROM int(5) ,
  HOUSE_NUMBER_TO INT(5),
   RANGE_INDICATOR CHAR(1),
   STREET_ID INT(6),
   PLACE_ID INT(6),
   CITY_ID INT(6),
  PROVINCE_CODE CHAR(1),
 PRIMARY KEY (TYPE, POSTCODE_HOUSENO_ID),
 FOREIGN KEY(STREET_ID) REFERENCES mut_straat(STREET_ID),
 FOREIGN KEY(PLACE_ID) REFERENCES mut_plaats(PLACE_ID),
 FOREIGN KEY(CITY_ID) REFERENCES mut_gemeente(CITY_ID),
  FOREIGN KEY(PROVINCE_CODE) REFERENCES mut_province(PROVINCE_CODE)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS = 1;